
CREATE SEQUENCE rpt01_id_sequence START 1;
-- 建第一张表 法人单位经济指标
CREATE TABLE "RPT01" (
  id INTEGER DEFAULT nextval('rpt01_id_sequence'),
  "统一社会信用代码"      TEXT NOT NULL UNIQUE,
  "单位详细名称"          TEXT,
  "数据来源"              TEXT,
  "是否一套表单位"      BOOLEAN,
  "经营地 - 省（自治区、直辖市）"  TEXT,
  "经营地 - 市（地、州、盟）"      TEXT,
  "经营地 - 县（区、市、旗）"      TEXT,
  "经营地 - 乡（镇、街道办事处）"  TEXT,
  "是否与单位所在地详细地址一致"   TEXT,
  "注册地 - 省（自治区、直辖市）"  TEXT,
  "注册地 - 市（地、州、盟）"      TEXT,
  "注册地 - 县（区、市、旗）"      TEXT,
  "注册地 - 乡（镇、街道办事处）"  TEXT,
  "机构类型（代码）"      TEXT,
  "机构类型（文字）"      TEXT,
  "登记注册类别（代码）"  TEXT,
  "登记注册类别（文字）"  TEXT,
  "行业代码"              TEXT,
  "专业分类"              TEXT,
  "产业"                  TEXT,
  "行业门类"              TEXT,
  "行业大类"              TEXT,
  "行业中类"              TEXT,
  "行业小类"              TEXT,
  "主要业务活动"              TEXT,
  "营业成本"              DECIMAL(18,2),
  "本年折旧"              DECIMAL(18,2),
  "资产总计"              DECIMAL(18,2),
  "负债合计"              DECIMAL(18,2),
  "营业收入"              DECIMAL(18,2),
  "税金及附加"            DECIMAL(18,2),
  "应交增值税"            DECIMAL(18,2),
  "应付职工薪酬"          DECIMAL(18,2),
  "营业利润"              DECIMAL(18,2),
  "资产减值损失"          DECIMAL(18,2),
  "信用减值损失"          DECIMAL(18,2),
  "投资收益"              DECIMAL(18,2),
  "公允价值变动收益"      DECIMAL(18,2),
  "资产处置收益"          DECIMAL(18,2),
  "其他收益"              DECIMAL(18,2),
  "净敞口套期收益"        DECIMAL(18,2),
  "税收合计"              DECIMAL(18,2),
  "期末从业人数"          INTEGER,
  "其中女性从业人数"      INTEGER,
  "研发人员数"            INTEGER,
  "研发费用"              DECIMAL(18,2),
  "专利申请数"            INTEGER,
  "专利授权数"            INTEGER,
  "增加值"                DECIMAL(18,2),
  "工业总产值"                DECIMAL(18,2),
  "单位规模（代码）"      TEXT,
  "单位规模（文字）"      TEXT
);

-- 给整张表加备注（可选）
COMMENT ON TABLE "RPT01" IS '法人单位经济指标';

-- 第二张：产业活动单位
CREATE SEQUENCE rpt02_id_sequence START 1;
CREATE TABLE "RPT02" (
  id INTEGER DEFAULT nextval('rpt02_id_sequence'),
  "统一社会信用代码"      TEXT,
  "单位详细名称"          TEXT,
  "数据来源"              TEXT,
  "是否一套表单位"      BOOLEAN,
  "经营地 - 省（自治区、直辖市）"  TEXT,
  "经营地 - 市（地、州、盟）"      TEXT,
  "经营地 - 县（区、市、旗）"      TEXT,
  "经营地 - 乡（镇、街道办事处）"  TEXT,
  "是否与单位所在地详细地址一致"   TEXT,
  "注册地 - 省（自治区、直辖市）"  TEXT,
  "注册地 - 市（地、州、盟）"      TEXT,
  "注册地 - 县（区、市、旗）"      TEXT,
  "注册地 - 乡（镇、街道办事处）"  TEXT,
  "机构类型（代码）"      TEXT,
  "机构类型（文字）"      TEXT,
  "登记注册类别（代码）"  TEXT,
  "登记注册类别（文字）"  TEXT,
  "行业代码"              TEXT,
  "专业分类"              TEXT,
  "产业"                  TEXT,
  "行业门类"              TEXT,
  "行业大类"              TEXT,
  "行业中类"              TEXT,
  "行业小类"              TEXT,
  "主要业务活动"              TEXT,
  "法人单位详细名称"      TEXT,
  "法人单位详细地址"      TEXT,
  "法人单位区划代码"      TEXT,
  "从业人员期末人数"      TEXT,
  "从业人员期末人数其中女性"      TEXT,
  "经营性单位收入"      DECIMAL(18,2),
  "非经营性单位支出 （费用）"      DECIMAL(18,2)

);

COMMENT ON TABLE "RPT02" IS '产业活动单位';

-- 第三张：国民经济代码表-产业分类

CREATE SEQUENCE rpt03_id_sequence START 1;
CREATE TABLE "RPT03" (
  id INTEGER DEFAULT nextval('rpt03_id_sequence'),
  "统一社会信用代码"      TEXT,
  "单位详细名称"          TEXT,
  "数据来源"              TEXT,
  "是否一套表单位"      BOOLEAN,
  "经营地 - 省（自治区、直辖市）"  TEXT,
  "经营地 - 市（地、州、盟）"      TEXT,
  "经营地 - 县（区、市、旗）"      TEXT,
  "经营地 - 乡（镇、街道办事处）"  TEXT,
  "是否与单位所在地详细地址一致"   TEXT,
  "注册地 - 省（自治区、直辖市）"  TEXT,
  "注册地 - 市（地、州、盟）"      TEXT,
  "注册地 - 县（区、市、旗）"      TEXT,
  "注册地 - 乡（镇、街道办事处）"  TEXT,
  "机构类型（代码）"      TEXT,
  "机构类型（文字）"      TEXT,
  "登记注册类别（代码）"  TEXT,
  "登记注册类别（文字）"  TEXT,
  "行业代码"              TEXT,
  "专业分类"              TEXT,
  "产业"                  TEXT,
  "行业门类"              TEXT,
  "行业大类"              TEXT,
  "行业中类"              TEXT,
  "行业小类"              TEXT,
  "主要业务活动"              TEXT,
  "营业成本"              DECIMAL(18,2),
  "本年折旧"              DECIMAL(18,2),
  "资产总计"              DECIMAL(18,2),
  "负债合计"              DECIMAL(18,2),
  "营业收入"              DECIMAL(18,2),
  "税金及附加"            DECIMAL(18,2),
  "应交增值税"            DECIMAL(18,2),
  "应付职工薪酬"          DECIMAL(18,2),
  "营业利润"              DECIMAL(18,2),
  "资产减值损失"          DECIMAL(18,2),
  "信用减值损失"          DECIMAL(18,2),
  "投资收益"              DECIMAL(18,2),
  "公允价值变动收益"      DECIMAL(18,2),
  "资产处置收益"          DECIMAL(18,2),
  "其他收益"              DECIMAL(18,2),
  "净敞口套期收益"        DECIMAL(18,2),
  "税收合计"              DECIMAL(18,2),
  "期末从业人数"          INTEGER,
  "其中女性从业人数"      INTEGER,
  "研发人员数"            INTEGER,
  "研发费用"              DECIMAL(18,2),
  "专利申请数"            INTEGER,
  "专利授权数"            INTEGER,
  "增加值"                DECIMAL(18,2),
  "单位规模（代码）"      TEXT,
  "单位规模（文字）"      TEXT,
  "产业分类"             TEXT,
  "产业领域"             TEXT,
  "产业大类"             TEXT,
  "产业中类"             TEXT,
  "产业小类"             TEXT,
);

COMMENT ON TABLE "RPT03" IS '法人单位产业分类表';


-- 第四张：产业活动单位
CREATE SEQUENCE rpt04_id_sequence START 1;
CREATE TABLE "RPT04" (
  id INTEGER DEFAULT nextval('rpt04_id_sequence'),
  "统一社会信用代码"      TEXT,
  "单位详细名称"          TEXT,
  "经营地 - 省（自治区、直辖市）"  TEXT,
  "经营地 - 市（地、州、盟）"      TEXT,
  "经营地 - 县（区、市、旗）"      TEXT,
  "经营地 - 乡（镇、街道办事处）"  TEXT,
  "是否与单位所在地详细地址一致"   TEXT,
  "注册地 - 省（自治区、直辖市）"  TEXT,
  "注册地 - 市（地、州、盟）"      TEXT,
  "注册地 - 县（区、市、旗）"      TEXT,
  "注册地 - 乡（镇、街道办事处）"  TEXT,
  "机构类型（代码）"      TEXT,
  "机构类型（文字）"      TEXT,
  "登记注册类别（代码）"  TEXT,
  "登记注册类别（文字）"  TEXT,
  "行业代码"              TEXT,
  "专业分类"              TEXT,
  "产业"                  TEXT,
  "行业门类"              TEXT,
  "行业大类"              TEXT,
  "行业中类"              TEXT,
  "行业小类"              TEXT,
  "主要业务活动"              TEXT,
  "法人单位详细名称"      TEXT,
  "法人单位详细地址"      TEXT,
  "法人单位区划代码"      TEXT,
  "从业人员期末人数"      TEXT,
  "从业人员期末人数其中女性"      TEXT,
  "经营性单位收入"      DECIMAL(18,2),
  "非经营性单位支出 （费用）"      DECIMAL(18,2),
  "产业分类"             TEXT,
  "产业领域"             TEXT,
  "产业大类"             TEXT,
  "产业中类"             TEXT,
  "产业小类"             TEXT,


);

COMMENT ON TABLE "RPT04" IS '产业活动单位产业分类表';
